---
title: "Assignment_4_2064_Huamani2"
author: "Javier Huamani"
date: "10/25/2021"
output: html_document
---

# Part 1

## Prepared EM Functions 


```{r}
Estep <- function(data, G, para){
  # Your Code
  # Return the n-by-G probability matrix
  n = dim(data)[1]
  z = outer(1:n, 1:G,FUN = Vectorize(function(i, j) 
  -(1/2) * as.matrix(data[i,] - para$mean[,j]) %*% solve(para$Sigma) %*% t(as.matrix(data[i,] - para$mean[,j])) + log(para$prob[j]) )
  )
  
  # Subtracting max value of z to handle underflow problem
  z_max = apply(z, 1, max)
  z = exp(z - z_max) / rowSums(exp(z - z_max))
  
  z
  }

Mstep <- function(data, G, para, post.prob){ 
  # Your Code
  # Return the updated parameters
  n = dim(data)[1]
  d = dim(data)[2]
  
  para$prob = colSums(post.prob) / n
  
  para$mean = outer(1:d, 1:G,FUN = Vectorize(function(i, j) 
  sum(as.matrix(post.prob[,j]*data[,i])) / sum(as.matrix(post.prob[,j]))
    ) )
  
  para$Sigma = matrix(0,d,d)
  
  for (g in 1:G){
    for (i in 1:n){
      para$Sigma = para$Sigma + (t(data[i,]) - para$mean[,g]) %*% t(t(data[i,]) - para$mean[,g]) * post.prob[i,g]
    }
  }
  para$Sigma = para$Sigma / n

  para
  }

myEM <- function(data, itmax, G, para){
  # itmax: num of iterations
  # G:     num of components
  # para:  list of parameters (prob, mean, Sigma)
  for(t in 1:itmax){
    post.prob <- Estep(data, G, para)
    para <- Mstep(data, G, para, post.prob)
  }
  return(para)
}
```

```{r}
options(digits=8)
options()$digits
```

## Test Functions

```{r}
library(mclust)
dim(faithful)
head(faithful)
n = nrow(faithful)
```

### Two Clusters


```{r}
K <- 2
set.seed(2064)  
gID <- sample(1:K, n, replace = TRUE)
Z <- matrix(0, n, K)
for(k in 1:K)
  Z[gID == k, k] <- 1 
ini0 <- mstep(modelName="EEE", faithful , Z)$parameters
```

```{r}
para0 <- list(prob = ini0$pro, 
              mean = ini0$mean, 
              Sigma = ini0$variance$Sigma)
para0
```


```{r}
myEM(data=faithful, itmax=20, G=K, para=para0)
```


```{r}
Rout <- em(modelName = "EEE", data = faithful,
           control = emControl(eps=0, tol=0, itmax = 20), 
           parameters = ini0)$parameters
list(Rout$pro, Rout$mean, Rout$variance$Sigma)
```


### Three Clusters

```{r}
K <- 3
gID <- sample(1:K, n, replace = TRUE)
Z <- matrix(0, n, K)
for(k in 1:K)
  Z[gID == k, k] <- 1 
ini0 <- mstep(modelName="EEE", faithful , Z)$parameters
para0 <- list(prob = ini0$pro, 
              mean = ini0$mean, 
              Sigma = ini0$variance$Sigma)
para0
```


```{r}
myEM(data=faithful, itmax=20, G=K, para=para0)
```


```{r}
Rout <- em(modelName = "EEE", data = faithful,
           control = emControl(eps=0, tol=0, itmax = 20), 
           parameters = ini0)$parameters
list(Rout$pro, Rout$mean, Rout$variance$Sigma)
```

